run:
  timeout: 3m

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    mi-complexity: 15
  gocritic:
    disabled-checks:
      - ifElseChain

linters:
  enable:
    - megacheck
    - govet
    - golint
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - goimports
    - whitespace
    - misspell
